web:
    build: .
    links:
        - db
    ports:
        - "30082:80"
    volumes:
        - ./src/sqlInjection3:/var/www/html
db:
    image: mysql:5.6
    volumes:
        - ./db:/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    expose:
        - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: "********"
        MYSQL_USER: bbb
        MYSQL_DATABASE: aaa
        MYSQL_PASSWORD: ccc
