web:
    build: .
    links:
        - db
    ports:
        - "10080:80"
    volumes:
        - ./src:/var/www/html
db:
    image: mysql:5.6
    volumes:
        - ./db:/var/lib/mysql
    expose:
        - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: "********"
        MYSQL_USER: bbb
        MYSQL_DATABASE: aaa
        MYSQL_PASSWORD: ccc
